env:
  commonjs: true
  es2020: true
  node: true
extends:
  - prettier
  - airbnb-base
plugins:
  - prettier
parserOptions:
  ecmaVersion: 11
rules:
  prettier/prettier: "error"
  no-param-reassign: "off"
  implicit-arrow-linebreak: "off"
