-- MySQL Script generated by MySQL Workbench
-- ter 04 ago 2020 22:17:41 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema toktiket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema toktiket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toktiket` DEFAULT CHARACTER SET utf8 ;
USE `toktiket` ;

-- -----------------------------------------------------
-- Table `toktiket`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toktiket`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `commenter_id` INT UNSIGNED NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_comments_user_idx` (`commenter_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comments_user`
    FOREIGN KEY (`commenter_id`)
    REFERENCES `toktiket`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toktiket`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toktiket`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `external_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toktiket`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toktiket`.`ticket` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `external_id` VARCHAR(40) NOT NULL,
  `description` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `submitter_id` INT UNSIGNED NOT NULL,
  `assignee_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ticketcol_UNIQUE` (`external_id` ASC) VISIBLE,
  INDEX `fk_tkt_user_createdby_idx` (`submitter_id` ASC) VISIBLE,
  INDEX `fk_tkt_user_assigned_to_idx` (`assignee_id` ASC) VISIBLE,
  CONSTRAINT `fk_tkt_user_createdby`
    FOREIGN KEY (`submitter_id`)
    REFERENCES `toktiket`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tkt_user_assigned_to`
    FOREIGN KEY (`assignee_id`)
    REFERENCES `toktiket`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toktiket`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toktiket`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` BINARY(60) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toktiket`.`usergroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toktiket`.`usergroup` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toktiket`.`usergroup_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toktiket`.`usergroup_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_group_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_group_id`, `user_id`),
  INDEX `fk_user_group_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_group_has_user_user_group1_idx` (`user_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_group_has_user_user_group1`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `toktiket`.`usergroup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_group_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `toktiket`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toktiket`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toktiket`.`user_roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `roles_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`, `roles_id`),
  INDEX `fk_user_has_roles_roles1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_user_has_roles_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_roles_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `toktiket`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `toktiket`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
